### ISSUE TITLE
Complete blank window

### ISSUE THREAD

**Issue by abuhuraira0099** [flathub/dev.linwood.butterfly#2]
I installed the app from the Flathub remote. I am running Gnome 43  beta (wayland) on Fedora 37 (prerelease). 

After launching the app it shows nothing but a complete blank window.
![Screenshot from 2022-08-15 19-34-22](https://user-images.githubusercontent.com/79898595/184646585-bb2ab16e-eda2-48c2-a1c8-24f9b6416dab.png)

**Comment by CodeDoctorDE** [comment]
Hello,
I pushed a new update for flatpak. Maybe this helps (it should be updated to 1.4.2 in the next days)

**Comment by CodeDoctorDE** [comment]
The next version is online. Does it solve your issue?

**Comment by abuhuraira0099** [comment]
> The next version is online. Does it solve your issue?

The update did not solve the issue.

**Comment by abuhuraira0099** [comment]
I tried running it from the terminal, it says:
```
** (butterfly:2): WARNING **: 11:25:44.836: Failed to start Flutter renderer: Unable to create a GL context
```

**Comment by CodeDoctorDE** [comment]
Which graphics card do you use and which driver version?
